name: Auto Build Termux Boot Apk
on:
   workflow_dispatch:
   repository_dispatch:
    types: start auto build Boot

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "设置应用名称变量"
        run: echo 'APP_NAME=termux_boot' >> $GITHUB_ENV

      - name: "克隆 Termux-Boot 仓库"
        run: git clone https://github.com/termux/termux-boot ${{ env.APP_NAME }} 

      - name: "执行脚本"
        run: bash ./script/run_build.sh ${{ env.APP_NAME }} 

      - name: "上传构建产物"
        uses: actions/upload-artifact@v4 
        with:
          name: ${{ env.APP_NAME }}
          path: ./${{ env.APP_NAME }}/app/build/outputs/apk/debug/*debug.apk 

      - name: "上传Apk到蓝奏云"
        run: |
          ${{secrets.LZY_UPDATE}}
          up_lzy ${{ env.APP_NAME }}_*.apk
