name: Auto Build Termux App Apk
on:
   workflow_dispatch:
   repository_dispatch:
    types: start auto build App

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "设置应用名称变量"
        run: echo 'APP_NAME=termux_app' >> $GITHUB_ENV 

      - name: "克隆 Termux-App 仓库"
        run: |
          tag_name=$(curl -s "https://api.github.com/repos/termux/termux-app/releases" |jq -r .[0].'tag_name') 
          git clone -b ${tag_name} https://github.com/termux/termux-app termux_app 

      - name: "执行脚本"
        run: bash ./script/run_build.sh ${{ env.APP_NAME }} termuxfy.sh 

      - name: "上传构建产物"
        uses: actions/upload-artifact@v4 
        with:
          name: ${{ env.APP_NAME }}_arm64
          path: ./${{ env.APP_NAME }}/app/build/outputs/apk/debug/*arm64-v8a.apk 

      - name: "上传Apk到蓝奏云"
        run: |
          ${{secrets.LZY_UPDATE}}
          up_lzy ${{ env.APP_NAME }}_*.apk
